# CMake generated Testfile for 
# Source directory: E:/Codes/clion/grammar/dependency/leveldb-1.23
# Build directory: E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/c_test.exe")
set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;341;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(fault_injection_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/fault_injection_test.exe")
set_tests_properties(fault_injection_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;342;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(issue178_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/issue178_test.exe")
set_tests_properties(issue178_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;344;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(issue200_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/issue200_test.exe")
set_tests_properties(issue200_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;345;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(issue320_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/issue320_test.exe")
set_tests_properties(issue320_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;346;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(env_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/env_test.exe")
set_tests_properties(env_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;348;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(status_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/status_test.exe")
set_tests_properties(status_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;349;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(no_destructor_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/no_destructor_test.exe")
set_tests_properties(no_destructor_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;350;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(autocompact_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/autocompact_test.exe")
set_tests_properties(autocompact_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;353;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(corruption_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/corruption_test.exe")
set_tests_properties(corruption_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;354;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(db_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/db_test.exe")
set_tests_properties(db_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;355;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(dbformat_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/dbformat_test.exe")
set_tests_properties(dbformat_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;356;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(filename_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/filename_test.exe")
set_tests_properties(filename_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;357;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(log_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/log_test.exe")
set_tests_properties(log_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;358;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(recovery_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/recovery_test.exe")
set_tests_properties(recovery_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;359;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(skiplist_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/skiplist_test.exe")
set_tests_properties(skiplist_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;360;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(version_edit_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/version_edit_test.exe")
set_tests_properties(version_edit_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;361;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(version_set_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/version_set_test.exe")
set_tests_properties(version_set_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;362;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(write_batch_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/write_batch_test.exe")
set_tests_properties(write_batch_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;363;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(memenv_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/memenv_test.exe")
set_tests_properties(memenv_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;365;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(filter_block_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/filter_block_test.exe")
set_tests_properties(filter_block_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;367;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(table_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/table_test.exe")
set_tests_properties(table_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;368;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(arena_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/arena_test.exe")
set_tests_properties(arena_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;370;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(bloom_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/bloom_test.exe")
set_tests_properties(bloom_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;371;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(cache_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/cache_test.exe")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;372;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(coding_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/coding_test.exe")
set_tests_properties(coding_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;373;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(crc32c_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/crc32c_test.exe")
set_tests_properties(crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;374;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(hash_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/hash_test.exe")
set_tests_properties(hash_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;375;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(logging_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/logging_test.exe")
set_tests_properties(logging_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;376;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
add_test(env_windows_test "E:/Codes/clion/grammar/dependency/leveldb-1.23/build_vs/env_windows_test.exe")
set_tests_properties(env_windows_test PROPERTIES  _BACKTRACE_TRIPLES "E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;338;add_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;381;leveldb_test;E:/Codes/clion/grammar/dependency/leveldb-1.23/CMakeLists.txt;0;")
subdirs("third_party/googletest")
subdirs("third_party/benchmark")
